# Generated by Django 5.1.3 on 2025-02-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
