# Generated by Django 5.1.3 on 2025-02-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_no',
        ),
    ]
