# Generated by Django 5.1.3 on 2024-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0002_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.URLField(default='event_images/default.png'),
        ),
    ]
