# Generated by Django 5.1.3 on 2024-12-06 16:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0003_alter_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('age_bracket', models.CharField(choices=[('16-18', '16-18'), ('19-21', '19-21'), ('22-24', '22-24'), ('25+', '25 and above')], max_length=20)),
                ('year_of_study', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('educational_level', models.CharField(choices=[('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_3', 'Year 3'), ('year_4', 'Year 4'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Innovation_WebApp.events')),
            ],
        ),
    ]
