# Generated by Django 5.1.3 on 2024-12-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0006_communitycategory_communityprofile_communitysession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='category',
        ),
        migrations.DeleteModel(
            name='CommunityCategory',
        ),
    ]
