# Generated by Django 5.1.3 on 2024-12-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0008_communitymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymember',
            name='community',
        ),
    ]
