# Generated by Django 5.1.3 on 2024-12-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0011_remove_communityprofile_total_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
    ]
