# Generated by Django 5.1.3 on 2025-02-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0013_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='registration_link',
        ),
    ]
