# Generated by Django 5.1.3 on 2025-02-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0015_events_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='age_bracket',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='expectations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='educational_level',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=20),
        ),
    ]
