# Generated by Django 5.1.3 on 2025-02-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0016_remove_eventregistration_age_bracket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='uid',
            field=models.EmailField(default='ondeyostephen0@gmail.com', editable=False, max_length=254, primary_key=True, serialize=False),
        ),
    ]
