# Generated by Django 5.1.3 on 2025-02-05 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0018_remove_eventregistration_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='uid',
            field=models.EmailField(default='ondeyostephen0@gmail.com', editable=False, max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
