# Generated by Django 5.1.3 on 2025-02-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0021_remove_communityprofile_treasurer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='image_field',
        ),
    ]
