# Generated by Django 5.1.3 on 2025-02-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0022_rename_image_events_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='image_field',
            new_name='image_url',
        ),
    ]
