# Generated by Django 5.1.3 on 2025-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0023_rename_image_field_events_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things')], default='Web Development', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('email', 'event')},
        ),
    ]
