# Generated by Django 5.1.3 on 2025-02-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemember',
            name='community',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='AboutUs.community'),
        ),
    ]
