# Generated by Django 5.1.3 on 2025-02-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_executivemember_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='AboutUs.club'),
            preserve_default=False,
        ),
    ]
