# Generated by Django 5.1.3 on 2025-02-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0005_alter_community_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='description',
            new_name='about_us',
        ),
        migrations.RemoveField(
            model_name='executivemember',
            name='image',
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='AboutUs.community'),
        ),
    ]
