# Generated by Django 5.1.3 on 2024-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('developer_id', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=1000)),
            ],
        ),
    ]
