# Generated by Django 5.1.3 on 2024-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('developer_id', 'application_name', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['developer_id', 'application_name', 'is_active'], name='developers__develop_8dea6f_idx'),
        ),
    ]
