# Generated by Django 5.1.3 on 2024-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_alter_apikey_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='developers__develop_8dea6f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('developer_id', 'application_name')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['developer_id', 'application_name'], name='developers__develop_5ad1b7_idx'),
        ),
    ]
